# Generated by Django 3.0 on 2020-01-15 14:39

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_year', models.TextField(blank=True, default=api.models.get_business_year_default, verbose_name='사업년도')),
                ('teams', models.CharField(blank=True, default='', max_length=100, verbose_name='시공 목록')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': '시공'}, on_delete=django.db.models.deletion.CASCADE, related_name='installer', to=settings.AUTH_USER_MODEL, verbose_name='시공 연결된 아이디')),
            ],
            options={
                'verbose_name': '시공',
                'verbose_name_plural': '시공 목록',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='installer',
            field=models.ForeignKey(blank=True, help_text='시공', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Installer', verbose_name='시공'),
        ),
    ]
